[package]
name = "monty"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
panic = 'abort'
strip = true
lto = true
codegen-units = 1

[features]
ataxx = []
shatranj = []

[dependencies]
goober = { git = 'https://github.com/jw1912/goober.git' }

[workspace]
members = ["datagen", "train/policy", "train/value"]
resolver = "2"
