[package]
name = "monty-train"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
monty-core = { path = "../monty-core" }
monty-engine = { path = "../monty-engine" }
goober = { git = 'https://github.com/jw1912/goober.git' }
