[package]
name = "train"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
bullet = { package = "bullet_lib", version = "1.0.0", features = ["cuda"] }
datagen = { path = "../datagen" }
monty = { path = "../" }
goober = { git = 'https://github.com/jw1912/goober.git' }
